export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      participants: { Row: { id: string; registration_number: string; full_name: string; email: string; qr_token_hash: string; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["participants"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["participants"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["participants"]["Insert"]>; Relationships: [] };
      volunteers: { Row: { id: string; email: string; name: string; role: "ADMIN" | "VOLUNTEER"; is_active: boolean; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["volunteers"]["Row"], "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["volunteers"]["Row"], "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["volunteers"]["Insert"]>; Relationships: [] };
      teams: { Row: { id: string; team_number: number; team_name: string; created_by: string; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["teams"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["teams"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["teams"]["Insert"]>; Relationships: [] };
      team_members: { Row: { team_id: string; participant_id: string; added_by: string; created_at: string }; Insert: Omit<Database["public"]["Tables"]["team_members"]["Row"], "created_at"> & Partial<Pick<Database["public"]["Tables"]["team_members"]["Row"], "created_at">>; Update: Partial<Database["public"]["Tables"]["team_members"]["Insert"]>; Relationships: [] };
      attendance: { Row: { id: string; participant_id: string; checkpoint: 1 | 2 | 3; recorded_by: string; recorded_at: string; device_id: string; created_at: string }; Insert: Omit<Database["public"]["Tables"]["attendance"]["Row"], "id" | "created_at"> & Partial<Pick<Database["public"]["Tables"]["attendance"]["Row"], "id" | "created_at">>; Update: Partial<Database["public"]["Tables"]["attendance"]["Insert"]>; Relationships: [] };
      sync_operations: { Row: { id: string; operation_id: string; device_id: string; volunteer_id: string; operation_type: "CREATE_TEAM" | "ADD_TEAM_MEMBER" | "RECORD_ATTENDANCE"; payload: Json; status: "PENDING" | "APPLIED" | "CONFLICT" | "FAILED"; created_at: string; processed_at: string | null }; Insert: Omit<Database["public"]["Tables"]["sync_operations"]["Row"], "id" | "created_at"> & Partial<Pick<Database["public"]["Tables"]["sync_operations"]["Row"], "id" | "created_at">>; Update: Partial<Database["public"]["Tables"]["sync_operations"]["Insert"]>; Relationships: [] };
      audit_logs: { Row: { id: string; actor_id: string | null; action: string; target_type: string; target_id: string | null; metadata: Json; created_at: string }; Insert: Omit<Database["public"]["Tables"]["audit_logs"]["Row"], "id" | "created_at"> & Partial<Pick<Database["public"]["Tables"]["audit_logs"]["Row"], "id" | "created_at">>; Update: Partial<Database["public"]["Tables"]["audit_logs"]["Insert"]>; Relationships: [] };
      pass_deliveries: { Row: { id: string; participant_id: string; email: string; status: "PENDING" | "SENT" | "FAILED"; provider_message_id: string | null; attempts: number; sent_at: string | null; last_error: string | null; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["pass_deliveries"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["pass_deliveries"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["pass_deliveries"]["Insert"]>; Relationships: [] };
      event_config: { Row: { id: string; event_name: string; event_date: string | null; venue: string | null; is_active: boolean; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["event_config"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["event_config"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["event_config"]["Insert"]>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: { current_volunteer: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["volunteers"]["Row"][] }; is_active_volunteer: { Args: Record<string, never>; Returns: boolean }; is_admin: { Args: Record<string, never>; Returns: boolean } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};